### ISSUE TITLE
Add webhook alert notifications

### ISSUE THREAD

**Issue by wootwoot1234** [taskforcesh/issues#101]
Currently, I think it's only possible to get alerts via email, it would be great to be able to send webhooks to get them in slack/discord as well.

**Comment by manast** [comment]
Thanks for suggesting this feature. It has been considered already but it has not been prioritized yet.

**Comment by murbanowicz** [comment]
While I don't like posting "any updates on this?", it's been over 3 months since last activity here, so I would like to know what is the status of this.
Some sort of web hook notifications on alerts would be great. 
These days, emails are often checked from time to time and Slack or Discord or any other tools are much better to get people's attention.

**Comment by manast** [comment]
Done!

https://docs.taskforce.sh/monitoring/enable-notifications/slack

**Comment by wootwoot1234** [comment]
Will this also work for Discord?

https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html

**Comment by manast** [comment]
I am not familiar with discord, but the message is formatted using slack special blocks format so probably it will not look proper on discord.

**Comment by wootwoot1234** [comment]
It’s a very popular alternative to slack. Is it possible to add discord as
one of the options? I linked to the webhook format above. If not, it it
possible to give us the option to format our own webhook data?

**Comment by manast** [comment]
I will add support for Discord too, coming soon.

**Comment by wootwoot1234** [comment]
Thank you!!
