### ISSUE TITLE
bullmq support roadmap

### ISSUE THREAD

**Issue by sbleon** [taskforcesh/issues#43]
Hi! I'm wondering what the status and roadmap are for bullmq support. The UI seems to basically be working, in that I can see queues and jobs. I don't see any workers listed though, even though I have workers connected.

**Comment by manast** [comment]
Yes, since BullMQ uses basically the same data structures as Bull it almost work for all major features, but things like getting the workers or other things may not work at all. This is high in up in our list. We have a couple of things that are going to be launched first, then we will complete BullMQ support.

**Comment by sbleon** [comment]
Thanks, Manuel!

**Comment by manast** [comment]
@sbleon I have been testing with BullMQ and so far no issues. I cannot reproduce the empty workers list that you mentioned before. Did you have multiple workers and do they share a connection maybe?

**Comment by sbleon** [comment]
Thanks, Manuel. I do have multiple workers sharing a connection. They're
both in the same Node process, though.

I'm not using taskforce.sh right now because I disabled public internet
access to my Redis and I haven't set up your connector software yet.

**Comment by manast** [comment]
BullMQ support has been live for a while now without any issues reported.
