### ISSUE TITLE
Payment for this subscription requires additional user action

### ISSUE THREAD

**Issue by SirBernardPhilip** [taskforcesh/issues#97]
I am trying to subscribe to BullMQ Pro using my credit card (I'm from Europe) but I am really struggling. I can add the card without problem but when I try to press "Update" the following error message pops up:
`
Error updating subscriptions: "Payment for this subscription requires additional user action before it can be completed successfully. Payment can be completed using the PaymentIntent associated with subscription.latest_invoice. Additional information is available here: https://stripe.com/docs/billing/subscriptions/overview#requires-action"
`

I don't have any kind of Adblock or anything that points towards a 3DSecure popup being blocked.

**Comment by manast** [comment]
I have spent quite some time trying to figure out this issue, and as far as I could understand, this happens when the card used requires SCA (3DS or similar), on EVERY transaction. This means that a card like this can not be used for subscriptions, since it will require manual approval for every invoice. I am not sure if the bank can whitelist some domains or how this could be handled, but from my side, for the moment I do not have any solution...

**Comment by manast** [comment]
After a dialog with Stripe, I made some improvements in the way the subscriptions are created and now they will trigger a pop-up to validate an SCA if needed. I hope this will cover most of the cases where this was not working before.
